- name: install nginx
  hosts: web
  become: yes
  tasks: 
     - name: Install nginx
       ansible.builtin.package: # Use 'ansible.builtin.yum' or 'ansible.builtin.dnf' for RHEL/CentOS
        name: nginx
        state: present 


     - name: Ensure nginx is started and enabled
       ansible.builtin.service: # Use 'ansible.builtin.service' for older systems
        name: nginx
        state: started
        enabled: yes