- name: play level variables
  hosts: local
  connection: local
  vars:
    NAME: "prasanna"
    AGE: "22"
    COLOUR: "pink"
  tasks: 
  - name: print variables
    ansible.builtin.debug:
      msg: "My name is {{ NAME }}, My age is {{ AGE }} i am in {{ COLOUR }} color"  