- name: demo on data types
  hosts: local 
  connection: local
  vars: 
    PROGRAM: "DevSecOps with AWS" #string
    DURATION: 140 #int/number
    IS_LIVE: true #bool
    DETAILS: #map/dictionary
      MONTHS: 4
      TRAINER: "Siva"
    TOPICS: #list -/[]
    - linux
    - shell
    - ansible
  tasks:
  - name: print variable
    ansible.builtin.debug:
      msg: |
        Program: {{ PROGRAM }} 
        DURATION: {{ DURATION }}
        Is Live?: {{ IS_LIVE }}
        DETAILS: {{ DETAILS }}
        TOPICS: {{ TOPICS }}
      