- name: install package
  hosts: local
  connection: local
  task:
  - name: install packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - mysql
    - nginx
    - zip